// Command genref generates internal/attrs/references_gen.go from the
// "references" section of config/models.json. Single source of truth:
// edit the JSON, re-run `go generate ./internal/attrs` — never edit the
// generated file by hand.
//
// Validation: ref must be non-empty; material must be a canonical material;
// dial must be a canonical dial or "" (unknown dial = material still derived,
// dial left to title detection).
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"watchfetcher/internal/attrs"
)

type refJSON struct {
	Ref      string `json:"ref"`
	Dial     string `json:"dial"`
	Material string `json:"material"`
}

type config struct {
	References map[string]map[string][]refJSON `json:"references"`
}

func main() {
	configPath := flag.String("config", "config/models.json", "path to models.json")
	outPath := flag.String("out", "internal/attrs/references_gen.go", "output path for generated Go file")
	flag.Parse()

	raw, err := os.ReadFile(*configPath)
	if err != nil {
		fatal("read config:", err)
	}
	var cfg config
	if err := json.Unmarshal(raw, &cfg); err != nil {
		fatal("parse config:", err)
	}

	validDial := map[string]bool{"": true}
	for _, d := range attrs.Dials() {
		validDial[d] = true
	}
	validMaterial := map[string]bool{}
	for _, m := range attrs.Materials() {
		validMaterial[m] = true
	}

	type entry struct {
		Ref, Brand, Model, Dial, Material string
	}
	var entries []entry
	seen := map[string]string{} // ref -> brand/model for dup detection
	nRefs := 0
	for brand, models := range cfg.References {
		for model, refs := range models {
			for _, r := range refs {
				ref := strings.ToUpper(strings.TrimSpace(r.Ref))
				nRefs++
				if ref == "" {
					fatal(fmt.Sprintf("%s/%s: empty ref", brand, model))
				}
				dial := strings.ToLower(strings.TrimSpace(r.Dial))
				material := strings.ToLower(strings.TrimSpace(r.Material))
				if !validDial[dial] {
					fatal(fmt.Sprintf("%s %s: dial %q not canonical", brand, model, dial))
				}
				if !validMaterial[material] {
					fatal(fmt.Sprintf("%s %s: material %q not canonical", brand, model, material))
				}
				if prev, dup := seen[ref]; dup {
					fatal(fmt.Sprintf("duplicate ref %s (%s and %s)", ref, prev, brand+"/"+model))
				}
				seen[ref] = brand + "/" + model
				entries = append(entries, entry{ref, brand, model, dial, material})
			}
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Ref < entries[j].Ref })

	var b strings.Builder
	b.WriteString("// Code generated by tools/genref from config/models.json. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: go generate ./internal/attrs\n")
	b.WriteString("package attrs\n\n")
	b.WriteString("// refEntry is one factory SKU: ref -> {brand, model, dial, material}.\n")
	b.WriteString("// The reference is indivisible — dial and material are derived, never free.\n")
	b.WriteString("type refEntry struct {\n")
	b.WriteString("\tBrand    string\n\tModel    string\n\tDial     string\n\tMaterial string\n}\n\n")
	b.WriteString("// referenceIndex is keyed by uppercase reference number.\n")
	b.WriteString("var referenceIndex = map[string]refEntry{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%q: {%q, %q, %q, %q},\n", e.Ref, e.Brand, e.Model, e.Dial, e.Material)
	}
	b.WriteString("}\n")

	body := b.String()
	formatted, err := format.Source([]byte(body))
	if err != nil {
		fatal("gofmt generated source:", err)
	}
	if err := os.WriteFile(*outPath, formatted, 0644); err != nil {
		fatal("write:", err)
	}
	fmt.Printf("genref: wrote %d references (%d json entries) to %s\n", len(entries), nRefs, *outPath)
}

func fatal(args ...any) {
	fmt.Fprintln(os.Stderr, args...)
	os.Exit(1)
}
