-- 0003_seed_catalogue.sql — seed references + market-name aliases.
-- Source: legacy watchfetcher taxonomy (config/models.json), archived at
-- archive/legacy-v0. Aliases are the resolver cascade rung 3 (PLAN §7.1).
INSERT OR IGNORE INTO catalogue_references (ref, brand, family, dial, material, updated_at) VALUES
  ('126610LN','Rolex','Submariner Date','black','steel', strftime('%s','now')),
  ('126610LV','Rolex','Submariner Date','green','steel', strftime('%s','now')),
  ('126613LB','Rolex','Submariner Date','blue','two_tone', strftime('%s','now')),
  ('126613LN','Rolex','Submariner Date','black','two_tone', strftime('%s','now')),
  ('126618LB','Rolex','Submariner Date','blue','gold', strftime('%s','now')),
  ('116610LN','Rolex','Submariner Date','black','steel', strftime('%s','now')),
  ('116610LV','Rolex','Submariner Date','green','steel', strftime('%s','now')),
  ('124060','Rolex','Submariner No-Date','black','steel', strftime('%s','now')),
  ('114060','Rolex','Submariner No-Date','black','steel', strftime('%s','now')),
  ('14060M','Rolex','Submariner No-Date','black','steel', strftime('%s','now')),
  ('126710BLRO','Rolex','GMT-Master II','pepsi','steel', strftime('%s','now')),
  ('126710BLNR','Rolex','GMT-Master II','batman','steel', strftime('%s','now')),
  ('126711CHNR','Rolex','GMT-Master II','brown','two_tone', strftime('%s','now')),
  ('126715CHNR','Rolex','GMT-Master II','brown','gold', strftime('%s','now')),
  ('126718GRNR','Rolex','GMT-Master II','black','gold', strftime('%s','now')),
  ('126720VTNR','Rolex','GMT-Master II','black','steel', strftime('%s','now')),
  ('116710BLNR','Rolex','GMT-Master II','batman','steel', strftime('%s','now')),
  ('116710LN','Rolex','GMT-Master II','black','steel', strftime('%s','now')),
  ('116713LN','Rolex','GMT-Master II','black','two_tone', strftime('%s','now')),
  ('16710','Rolex','GMT-Master II','','steel', strftime('%s','now')),
  ('126500LN','Rolex','Cosmograph Daytona','','steel', strftime('%s','now')),
  ('126518LN','Rolex','Cosmograph Daytona','','gold', strftime('%s','now')),
  ('126519LN','Rolex','Cosmograph Daytona','','gold', strftime('%s','now')),
  ('116500LN','Rolex','Cosmograph Daytona','','steel', strftime('%s','now')),
  ('116520','Rolex','Cosmograph Daytona','','steel', strftime('%s','now')),
  ('116518LN','Rolex','Cosmograph Daytona','','gold', strftime('%s','now')),
  ('116506','Rolex','Cosmograph Daytona','blue','platinum', strftime('%s','now')),
  ('16520','Rolex','Cosmograph Daytona','','steel', strftime('%s','now')),
  ('126200','Rolex','Datejust','','steel', strftime('%s','now')),
  ('126234','Rolex','Datejust','','two_tone', strftime('%s','now')),
  ('126300','Rolex','Datejust','','steel', strftime('%s','now')),
  ('126334','Rolex','Datejust','','two_tone', strftime('%s','now')),
  ('116234','Rolex','Datejust','','two_tone', strftime('%s','now')),
  ('228238','Rolex','Day-Date','','gold', strftime('%s','now')),
  ('228239','Rolex','Day-Date','','gold', strftime('%s','now')),
  ('228235','Rolex','Day-Date','','gold', strftime('%s','now')),
  ('118238','Rolex','Day-Date','','gold', strftime('%s','now')),
  ('124270','Rolex','Explorer','black','steel', strftime('%s','now')),
  ('214270','Rolex','Explorer','black','steel', strftime('%s','now')),
  ('226570','Rolex','Explorer II','','steel', strftime('%s','now')),
  ('216570','Rolex','Explorer II','','steel', strftime('%s','now')),
  ('16570','Rolex','Explorer II','','steel', strftime('%s','now')),
  ('126600','Rolex','Sea-Dweller','black','steel', strftime('%s','now')),
  ('136660','Rolex','Sea-Dweller','black','steel', strftime('%s','now')),
  ('116660','Rolex','Sea-Dweller','black','steel', strftime('%s','now')),
  ('16600','Rolex','Sea-Dweller','black','steel', strftime('%s','now')),
  ('126622','Rolex','Yacht-Master','','steel', strftime('%s','now')),
  ('116622','Rolex','Yacht-Master','','steel', strftime('%s','now')),
  ('126900','Rolex','Air-King','black','steel', strftime('%s','now')),
  ('116900','Rolex','Air-King','black','steel', strftime('%s','now')),
  ('124300','Rolex','Oyster Perpetual','','steel', strftime('%s','now')),
  ('126000','Rolex','Oyster Perpetual','','steel', strftime('%s','now')),
  ('5711/1A-010','Patek Philippe','Nautilus','blue','steel', strftime('%s','now')),
  ('5711/1R-001','Patek Philippe','Nautilus','brown','gold', strftime('%s','now')),
  ('5811/1G-001','Patek Philippe','Nautilus','blue','gold', strftime('%s','now')),
  ('5990/1A-001','Patek Philippe','Nautilus','','steel', strftime('%s','now')),
  ('5712/1A-001','Patek Philippe','Nautilus','blue','steel', strftime('%s','now')),
  ('5980/1A-001','Patek Philippe','Nautilus','blue','steel', strftime('%s','now')),
  ('3800/1A','Patek Philippe','Nautilus','blue','steel', strftime('%s','now')),
  ('5167A-001','Patek Philippe','Aquanaut','black','steel', strftime('%s','now')),
  ('5165A-001','Patek Philippe','Aquanaut','black','steel', strftime('%s','now')),
  ('5168G-001','Patek Philippe','Aquanaut','blue','gold', strftime('%s','now')),
  ('5164A-001','Patek Philippe','Aquanaut','black','steel', strftime('%s','now')),
  ('5226G-001','Patek Philippe','Calatrava','black','gold', strftime('%s','now')),
  ('15500ST','Audemars Piguet','Royal Oak','','steel', strftime('%s','now')),
  ('15500OR','Audemars Piguet','Royal Oak','','gold', strftime('%s','now')),
  ('15510ST','Audemars Piguet','Royal Oak','','steel', strftime('%s','now')),
  ('16202ST','Audemars Piguet','Royal Oak','','steel', strftime('%s','now')),
  ('26240ST','Audemars Piguet','Royal Oak','','steel', strftime('%s','now')),
  ('15400ST','Audemars Piguet','Royal Oak','','steel', strftime('%s','now')),
  ('15202ST','Audemars Piguet','Royal Oak','','steel', strftime('%s','now')),
  ('26238ST','Audemars Piguet','Royal Oak Offshore','','steel', strftime('%s','now')),
  ('26470ST','Audemars Piguet','Royal Oak Offshore','','steel', strftime('%s','now')),
  ('310.30.42.50.01.001','Omega','Speedmaster Professional','black','steel', strftime('%s','now')),
  ('310.30.42.50.03.001','Omega','Speedmaster Professional','blue','steel', strftime('%s','now')),
  ('3570.50.00','Omega','Speedmaster Professional','black','steel', strftime('%s','now')),
  ('311.30.42.30.01.005','Omega','Speedmaster','black','steel', strftime('%s','now')),
  ('210.30.42.20.01.001','Omega','Seamaster Diver 300M','black','steel', strftime('%s','now')),
  ('210.30.42.20.03.001','Omega','Seamaster Diver 300M','blue','steel', strftime('%s','now')),
  ('2254.50.00','Omega','Seamaster Diver 300M','black','steel', strftime('%s','now')),
  ('220.10.41.21.03.001','Omega','Seamaster Aqua Terra','blue','steel', strftime('%s','now')),
  ('231.10.42.21.03.001','Omega','Seamaster Aqua Terra','blue','steel', strftime('%s','now')),
  ('215.30.44.21.01.001','Omega','Seamaster Planet Ocean','black','steel', strftime('%s','now')),
  ('215.30.44.21.03.001','Omega','Seamaster Planet Ocean','blue','steel', strftime('%s','now')),
  ('220.10.40.20.01.001','Omega','Railmaster','black','steel', strftime('%s','now')),
  ('79030N','Tudor','Black Bay 58','black','steel', strftime('%s','now')),
  ('79030B','Tudor','Black Bay 58','blue','steel', strftime('%s','now')),
  ('79830RB','Tudor','Black Bay GMT','pepsi','steel', strftime('%s','now')),
  ('79360N','Tudor','Black Bay Chrono','black','steel', strftime('%s','now')),
  ('79230N','Tudor','Black Bay','black','steel', strftime('%s','now')),
  ('79230R','Tudor','Black Bay','','steel', strftime('%s','now')),
  ('79000N','Tudor','Black Bay','black','steel', strftime('%s','now')),
  ('25600TN','Tudor','Pelagos','black','titanium', strftime('%s','now')),
  ('25600TB','Tudor','Pelagos','blue','titanium', strftime('%s','now')),
  ('79950','Tudor','Ranger','black','steel', strftime('%s','now')),
  ('WSSA0018','Cartier','Santos de Cartier','blue','steel', strftime('%s','now')),
  ('4500V/110A-B483','Vacheron Constantin','Overseas','blue','steel', strftime('%s','now')),
  ('PAM01312','Panerai','Luminor Marina','black','steel', strftime('%s','now')),
  ('IW329301','IWC','Big Pilot','black','steel', strftime('%s','now')),
  ('IW501001','IWC','Big Pilot','black','steel', strftime('%s','now')),
  ('SBGA211','Grand Seiko','Snowflake','silver','titanium', strftime('%s','now')),
  ('SBGA413','Grand Seiko','Snowflake','salmon','titanium', strftime('%s','now'));

INSERT OR IGNORE INTO catalogue_aliases (alias, ref, kind, added_by, created_at)
SELECT a.alias, a.ref, a.kind, 'seed', strftime('%s','now')
FROM (
  SELECT 'pepsi' AS alias, '126710BLRO' AS ref, 'nickname' AS kind UNION ALL
  SELECT 'batman', '126710BLNR', 'nickname' UNION ALL
  SELECT 'batgirl', '126710BLNR', 'nickname' UNION ALL
  SELECT 'sprite', '126720VTNR', 'nickname' UNION ALL
  SELECT 'rootbeer', '126711CHNR', 'nickname' UNION ALL
  SELECT 'hulk', '126610LV', 'nickname' UNION ALL
  SELECT 'kermit', '126610LV', 'nickname' UNION ALL
  SELECT 'panda', '126500LN', 'nickname' UNION ALL
  SELECT 'kona', '126600', 'nickname' UNION ALL
  SELECT 'pelagos right', '25600TB', 'market_name'
) a
JOIN catalogue_references cr ON cr.ref = a.ref;
